# Generated by Django 3.1.10 on 2021-09-23 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('menu', '0001_initial'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0005_standarpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StandarPage',
            new_name='StandardPage',
        ),
    ]
