# Generated by Django 3.1.10 on 2021-10-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210923_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home page Atlas RDV', 'verbose_name_plural': 'Accueil Bakery'},
        ),
    ]
